# Exclude unimportant files
require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  Include:
    - 'lib/**/*.rb'
    - 'test/**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'

  Exclude:
    - '**/.bundle/*'
    - '**/.git/*'
    - '**/.github/*'
    - '**/bin/**/*'
    - '**/coverage/**/*'
    - '**/docs/**/*'
    - '**/imagemagick/*'
    - '**/pkg/**/*'
    - '**/vendor/**/*'


# Disabled Cops
Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
