name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests and check formatting
    runs-on: ubuntu-latest
    env:
      imagemagick_version: 7.0.10-46

    steps:

    # - name: Install system dependencies
    #   run: sudo apt install webp libopenjp2-tools

    - run: git clone 'https://github.com/ImageMagick/ImageMagick' imagemagick --branch "$imagemagick_version"
      name: Clone Imagemagick
    - name: Install imagemagick
      working-directory: ./imagemagick
      run: |
        ./configure
        make
        sudo make install

    # - name: Cache Imagemagick build
    #   uses: actions/cache@v2
    #   with: 
    #     path: ./imagemagick
    #     # Key is the imagemagick version.
    #     key: imagemagick-{{ env.imagemagick_version }}

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Ruby
      # Version taken from .ruby-version file
      uses: ruby/setup-ruby@v1
      with: 
        bundler-cache: true


    - name: Install Ruby dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rake test

    - name: Check formatting
      run: bundle exec rake rubocop
