name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests and check formatting
    runs-on: ubuntu-latest
    env:
      imagemagick_version: 7.0.10-46

    steps:

    # - name: Install system dependencies
    #   run: sudo apt install webp libwebp6 libopenjp2-tools
    - run: mkdir -p cache-test
    - run: ls cache-test
    - run: touch cache-test/test1

    - uses: actions/cache@v2
      with:
        path: cache-test
        key: test1
        # key: imagemagick-${{ env.imagemagick_version }}

    - run: ls cache-test
    - run: touch cache-test/test2

    # - uses: actions/cache@v2
    #   with:
    #     path: ./imagemagick
    #     key: imagemagick-${{ env.imagemagick_version }}

    # - name: Install imagemagick
    #   run: |
    #     mkdir imagemagick
    #     cd imagemagick
    #     pwd
    #     git status || git clone 'https://github.com/ImageMagick/ImageMagick' ./ --branch "$imagemagick_version"
    #     ./configure
    #     make
    #     sudo make install
    #     sudo ldconfig /usr/local/lib

    # - run: convert --version

    # - name: Checkout repo
    #   uses: actions/checkout@v2

    # Version taken from .ruby-version file
    # - name: Install Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     bundler-cache: true

    # - name: Install required gems
    #   run: bundle install

    # - name: Run tests
    #   run: bundle exec rake test

    # - name: Check formatting
    #   run: bundle exec rake rubocop
